### PR TITLE
Update baselib_es_ES.ts

### PR DESCRIPTION
**Pull request by zinkro**
please ignore and delete this fork

### CODE REVIEW

**Comment by sboily** [comment]
Hello, why did you open a PR for translation. You only need to create your translation on transifex. And we will add the translation at the end of our iteration.
Thanks.

**Comment by sduthil** [comment]
As sboily said, you only need to translate on Transifex. We will update the translations just before the next release 15.12. That should happen at the end of next week. Thanks a lot for your contribution!

**Comment by zinkro** [comment]
Sorry, i make a mistake.

**Comment by sduthil** [comment]
I just updated the XiVO Client so that Spanish (Chile) is available (see 453ead7c4326957f601b1302124d43db5ea40f3a). Thanks again!

**Pull request closed without merging**
